language: crystal
services:
  - postgresql
before_script:
  - mysql -e 'create database crecto_test'
  - psql -c 'create database crecto_test;' -U postgres
  - psql $PG_URL < spec/migrations/pg_users.sql
env:
  - DB=postgresql
  - DB=mysql
